# F1 Dashboard

In [32]:
import pandas as pd
from glob import glob

In [33]:
drivers_map = {
    'VER': ('Max Verstappen', 'Red Bull'),
    'GAS': ('Pierre Gasly', 'Alpine'),
    'PER': ('Sergio Perez', 'Red Bull'),
    'ALO': ('Fernando Alonso', 'Aston Martin'),
    'LEC': ('Charles Leclerc', 'Ferrari'),
    'STR': ('Lance Stroll', 'Aston Martin'),
    'MAG': ('Kevin Magnussen', 'Haas'),
    'TSU': ('Yuki Tsunoda', 'Racing Bulls'),
    'ALB': ('Alexander Albon', 'Williams'),
    'ZHO': ('Zhou Guanyu', 'Kick Sauber'),
    'HUL': ('Nico Hulkenberg', 'Haas'),
    'LAW': ('Liam Lawson', 'Racing Bulls'),
    'NOR': ('Lando Norris', 'McLaren'),
    'COL': ('Franco Colapinto', 'Williams'),
    'HAM': ('Lewis Hamilton', 'Mercedes'),
    'SAI': ('Carlos Sainz', 'Ferrari'),
    'DOO': ('Jack Doohan', 'Alpine'),
    'RUS': ('George Russel', 'Mercedes'),
    'BOT': ('Valtteri Bottas', 'Kick Sauber'),
    'PIA': ('Oscar Piastri', 'McLaren'),
    'OCO': ('Esteban Ocon', 'Alpine'),
    'RIC': ('Daniel Ricciardo', 'Racing Bulls'),
    'SAR': ('Logan Sargeant', 'Williams'),
    'BEA': ('Oliver Bearman', 'Haas')
}

In [69]:
f1_team = (
    pd.concat(
        ((pd.read_csv(x)
        .assign(
            track=x.split('/')[1].split('2')[0].replace('_', ' ')
        ) for x in glob('data/*.csv'))),
        ignore_index=True, )
    .rename(columns=str.lower)
    .rename(
        columns={
            'sector1time': 'sector1',
            'sector2time': 'sector2',
            'sector3time': 'sector3',
        }
    )
    .query('laptime < 500 or laptime.isna()')
    .assign(
        full_name=lambda df: df['driver'].apply(lambda x: drivers_map[x][0]),
        team=lambda df: df['driver'].apply(lambda x: drivers_map[x][1]),
    )
)

f1_team

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
0,NOR,1.0,1.0,100.424,NaN,41.379,27.852,186.0,MEDIUM,Singapore,Lando Norris,McLaren
1,NOR,2.0,1.0,98.480,29.268,41.412,27.800,276.0,MEDIUM,Singapore,Lando Norris,McLaren
2,NOR,3.0,1.0,98.406,29.354,41.262,27.790,270.0,MEDIUM,Singapore,Lando Norris,McLaren
3,NOR,4.0,1.0,98.446,29.399,41.305,27.742,272.0,MEDIUM,Singapore,Lando Norris,McLaren
4,NOR,5.0,1.0,97.938,29.034,41.159,27.745,278.0,MEDIUM,Singapore,Lando Norris,McLaren
...,...,...,...,...,...,...,...,...,...,...,...,...
26829,RUS,30.0,4.0,101.237,31.859,41.018,28.360,300.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26830,RUS,31.0,4.0,101.902,31.950,41.210,28.742,299.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26831,RUS,32.0,4.0,103.085,32.488,41.387,29.210,290.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26832,RUS,33.0,4.0,106.221,32.329,41.835,32.057,262.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26833,GAS,1.0,1.0,NaN,NaN,NaN,NaN,NaN,MEDIUM,Great Britain,Pierre Gasly,Alpine

In [35]:
µ(
    f1_team.query('full_name == "Max Verstappen"')
    .groupby('track')
    .agg(
        position=('position', 'last')
    )
    .reset_index()
)

             track  position
0        Abu Dhabi       6.0
1           Austin       4.0
2        Australia       2.0
3          Austria       5.0
4       Azerbaijan       7.0
5          Barhain       1.0
6          Belgium       5.0
7           Brazil       1.0
8           Canada       1.0
9            China       1.0
10  Emilia Romagna       1.0
11   Great Britain       2.0
12         Hungary       5.0
13           Italy       6.0
14           Japan       1.0
15       Las Vegas       5.0
16          Mexico       6.0
17           Miami       2.0
18          Monaco       6.0
19      Netherland       2.0
20           Qatar       1.0
21    Saudi Arabia       1.0
22       Singapore       2.0
23           Spain       1.0

In [36]:
(
    f1_team.query('full_name == "Max Verstappen"')
    .groupby('track')
    .agg(
        best_lap=('laptime', 'min')
    )
    .reset_index()
)

             track  best_lap
0        Abu Dhabi    87.765
1           Austin    98.117
2        Australia    83.115
3          Austria    67.719
4       Azerbaijan   106.798
5          Barhain    92.608
6          Belgium   106.128
7           Brazil    80.472
8           Canada    75.569
9            China    98.406
10  Emilia Romagna    80.366
11   Great Britain    88.952
12         Hungary    80.908
13           Italy    81.745
14           Japan    93.706
15       Las Vegas    96.248
16          Mexico    80.872
17           Miami    91.261
18          Monaco    74.569
19      Netherland    74.752
20           Qatar    82.905
21    Saudi Arabia    92.608
22       Singapore    95.967
23           Spain    77.776

In [37]:
(
    pd.concat(
        ((pd.read_csv(x)
        .assign(
            track=x.split('/')[1].split('2')[0].replace('_', ' ')
        ) for x in glob('data/*.csv'))),
        ignore_index=True, )
    .rename(columns=str.lower)
    .rename(
        columns={
            'sector1time': 'sector1',
            'sector2time': 'sector2',
            'sector3time': 'sector3',
        }
    )
    .assign(
        full_name=lambda df: df['driver'].apply(lambda x: drivers_map[x][0]),
        team=lambda df: df['driver'].apply(lambda x: drivers_map[x][1]),
    )
)

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
0,NOR,1.0,1.0,100.424,NaN,41.379,27.852,186.0,MEDIUM,Singapore,Lando Norris,McLaren
1,NOR,2.0,1.0,98.480,29.268,41.412,27.800,276.0,MEDIUM,Singapore,Lando Norris,McLaren
2,NOR,3.0,1.0,98.406,29.354,41.262,27.790,270.0,MEDIUM,Singapore,Lando Norris,McLaren
3,NOR,4.0,1.0,98.446,29.399,41.305,27.742,272.0,MEDIUM,Singapore,Lando Norris,McLaren
4,NOR,5.0,1.0,97.938,29.034,41.159,27.745,278.0,MEDIUM,Singapore,Lando Norris,McLaren
...,...,...,...,...,...,...,...,...,...,...,...,...
26829,RUS,30.0,4.0,101.237,31.859,41.018,28.360,300.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26830,RUS,31.0,4.0,101.902,31.950,41.210,28.742,299.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26831,RUS,32.0,4.0,103.085,32.488,41.387,29.210,290.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26832,RUS,33.0,4.0,106.221,32.329,41.835,32.057,262.0,INTERMEDIATE,Great Britain,George Russel,Mercedes
26833,GAS,1.0,1.0,NaN,NaN,NaN,NaN,NaN,MEDIUM,Great Britain,Pierre Gasly,Alpine

In [38]:
f1_team.query('track == "Austin" and full_name == "Lewis Hamilton"')

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
2011,HAM,1.0,12.0,108.064,NaN,42.336,34.43,317.0,HARD,Austin,Lewis Hamilton,Mercedes

In [39]:
f1_team.loc[f1_team.groupby('track')['maxspeed'].idxmax()]

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
7801,PIA,38.0,14.0,88.238,17.672,37.733,32.833,341.0,HARD,Abu Dhabi,Oscar Piastri,McLaren
2077,RUS,9.0,16.0,101.913,27.220,40.168,34.525,344.0,HARD,Austin,George Russel,Mercedes
25437,HUL,41.0,10.0,82.016,28.708,17.905,35.403,326.0,HARD,Australia,Nico Hulkenberg,Haas
13559,HUL,2.0,8.0,70.217,17.533,31.155,21.529,325.0,MEDIUM,Austria,Nico Hulkenberg,Haas
2919,HAM,15.0,17.0,108.754,39.163,44.460,25.131,334.0,HARD,Azerbaijan,Lewis Hamilton,Mercedes
9087,SAI,17.0,4.0,95.507,30.202,41.758,23.547,332.0,HARD,Barhain,Carlos Sainz,Ferrari
24417,OCO,32.0,13.0,106.992,30.450,47.965,28.577,325.0,HARD,Belgium,Esteban Ocon,Alpine
8157,LEC,60.0,5.0,81.631,20.831,43.002,17.798,294.0,INTERMEDIATE,Brazil,Charles Leclerc,Ferrari
12397,MAG,70.0,12.0,77.110,22.203,24.468,30.439,347.0,MEDIUM,Canada,Kevin Magnussen,Haas
22185,STR,33.0,17.0,102.201,27.202,31.065,43.934,347.0,MEDIUM,China,Lance Stroll,Aston Martin
21386,MAG,61.0,13.0,81.750,25.626,28.748,27.376,304.0,HARD,Emilia Romagna,Kevin Magnussen,Haas
26716,PER,17.0,15.0,94.829,29.675,38.196,26.958,335.0,HARD,Great Britain,Sergio Perez,Red Bull
4983,RUS,70.0,8.0,84.063,29.633,30.728,23.702,316.0,HARD,Hungary,George Russel,Mercedes
6266,MAG,11.0,11.0,86.040,27.934,29.461,28.645,357.0,MEDIUM,Italy,Kevin Magnussen,Haas
11597,HUL,45.0,14.0,96.808,35.284,42.978,18.546,309.0,HARD,Japan,Nico Hulkenberg,Haas
10151,HAM,16.0,6.0,97.091,27.837,32.943,36.311,350.0,HARD,Las Vegas,Lewis Hamilton,Mercedes
3715,PIA,10.0,16.0,82.793,28.506,32.764,21.523,362.0,MEDIUM,Mexico,Oscar Piastri,McLaren
18606,STR,35.0,17.0,92.950,31.857,35.423,25.670,355.0,MEDIUM,Miami,Lance Stroll,Aston Martin
19943,HAM,78.0,7.0,76.355,19.818,35.947,20.590,289.0,HARD,Monaco,Lewis Hamilton,Mercedes
14942,SAI,47.0,6.0,75.105,25.329,27.337,22.439,335.0,HARD,Netherland,Carlos Sainz,Ferrari
18057,HAM,56.0,12.0,84.412,31.396,28.447,24.569,336.0,HARD,Qatar,Lewis Hamilton,Mercedes
23035,SAI,17.0,4.0,95.507,30.202,41.758,23.547,332.0,HARD,Saudi Arabia,Carlos Sainz,Ferrari
647,COL,31.0,12.0,100.451,30.385,42.358,27.708,305.0,HARD,Singapore,Franco Colapinto,Williams
17089,MAG,5.0,16.0,83.042,23.714,34.392,24.936,343.0,SOFT,Spain,Kevin Magnussen,Haas

In [40]:
f1_team.query("track == 'Great Britain'").groupby('full_name').agg(max_speed=('maxspeed', 'max'))

                  max_speed
full_name
Alexander Albon       331.0
Carlos Sainz          322.0
Charles Leclerc       328.0
Daniel Ricciardo      327.0
Esteban Ocon          332.0
Fernando Alonso       332.0
George Russel         309.0
Kevin Magnussen       334.0
Lance Stroll          328.0
Lando Norris          326.0
Lewis Hamilton        319.0
Logan Sargeant        329.0
Max Verstappen        327.0
Nico Hulkenberg       325.0
Oscar Piastri         329.0
Sergio Perez          335.0
Valtteri Bottas       322.0
Yuki Tsunoda          333.0
Zhou Guanyu           329.0

In [41]:
testName = "Max Verstappen"
testTrack = "Belgium"

In [42]:
(
    f1_team
    .query(f"full_name == '{testName}' and track == '{testTrack}'")
)

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
24166,VER,1.0,9.0,117.183,NaN,52.573,29.298,300.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24167,VER,2.0,8.0,109.828,30.820,49.592,29.416,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24168,VER,3.0,8.0,110.141,30.975,49.693,29.473,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24169,VER,4.0,8.0,110.055,31.020,49.636,29.399,306.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24170,VER,5.0,8.0,110.138,31.118,49.599,29.421,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24171,VER,6.0,8.0,110.073,30.920,49.795,29.358,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24172,VER,7.0,8.0,110.146,31.044,49.700,29.402,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24173,VER,8.0,8.0,110.094,30.957,49.759,29.378,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24174,VER,9.0,8.0,110.609,30.938,50.214,29.457,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24175,VER,10.0,8.0,114.655,31.005,49.825,33.825,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24176,VER,11.0,13.0,122.789,45.573,48.109,29.107,310.0,HARD,Belgium,Max Verstappen,Red Bull
24177,VER,12.0,10.0,108.403,30.615,48.559,29.229,315.0,HARD,Belgium,Max Verstappen,Red Bull
24178,VER,13.0,9.0,108.431,31.082,48.239,29.110,312.0,HARD,Belgium,Max Verstappen,Red Bull
24179,VER,14.0,8.0,108.153,30.851,48.222,29.080,NaN,HARD,Belgium,Max Verstappen,Red Bull
24180,VER,15.0,8.0,108.229,30.811,48.342,29.076,313.0,HARD,Belgium,Max Verstappen,Red Bull
24181,VER,16.0,7.0,108.509,30.808,48.571,29.130,315.0,HARD,Belgium,Max Verstappen,Red Bull
24182,VER,17.0,7.0,108.431,30.753,48.584,29.094,311.0,HARD,Belgium,Max Verstappen,Red Bull
24183,VER,18.0,7.0,108.896,30.775,48.975,29.146,313.0,HARD,Belgium,Max Verstappen,Red Bull
24184,VER,19.0,7.0,108.578,30.879,48.583,29.116,314.0,HARD,Belgium,Max Verstappen,Red Bull
24185,VER,20.0,7.0,109.134,30.947,48.912,29.275,311.0,HARD,Belgium,Max Verstappen,Red Bull
24186,VER,21.0,5.0,109.273,30.823,49.246,29.204,314.0,HARD,Belgium,Max Verstappen,Red Bull
24187,VER,22.0,5.0,108.448,31.091,48.204,29.153,313.0,HARD,Belgium,Max Verstappen,Red Bull
24188,VER,23.0,5.0,108.494,31.211,48.197,29.086,312.0,HARD,Belgium,Max Verstappen,Red Bull
24189,VER,24.0,5.0,108.154,31.173,48.096,28.885,313.0,HARD,Belgium,Max Verstappen,Red Bull
24190,VER,25.0,5.0,107.921,31.127,47.886,28.908,314.0,HARD,Belgium,Max Verstappen,Red Bull
24191,VER,26.0,4.0,107.815,31.124,47.815,28.876,NaN,HARD,Belgium,Max Verstappen,Red Bull
24192,VER,27.0,3.0,107.431,31.032,47.549,28.850,315.0,HARD,Belgium,Max Verstappen,Red Bull
24193,VER,28.0,4.0,112.026,31.021,47.724,33.281,NaN,HARD,Belgium,Max Verstappen,Red Bull
24194,VER,29.0,7.0,120.489,45.265,46.585,28.639,311.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24195,VER,30.0,5.0,106.447,30.611,47.026,28.810,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24196,VER,31.0,5.0,106.363,30.950,46.698,28.715,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24197,VER,32.0,5.0,106.128,30.875,46.512,28.741,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24198,VER,33.0,5.0,106.417,30.904,46.670,28.843,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24199,VER,34.0,5.0,106.630,30.957,46.821,28.852,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24200,VER,35.0,5.0,107.009,30.947,47.264,28.798,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24201,VER,36.0,5.0,107.156,30.906,47.253,28.997,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24202,VER,37.0,5.0,107.200,30.765,47.596,28.839,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24203,VER,38.0,5.0,107.177,30.850,47.473,28.854,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24204,VER,39.0,5.0,107.244,30.883,47.479,28.882,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24205,VER,40.0,5.0,107.227,30.646,47.673,28.908,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24206,VER,41.0,5.0,107.354,30.598,47.920,28.836,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24207,VER,42.0,5.0,107.387,30.637,47.949,28.801,319.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24208,VER,43.0,5.0,107.102,30.579,47.831,28.692,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24209,VER,44.0,5.0,106.899,30.605,47.569,28.725,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull

In [43]:
(
    f1_team
    .query(f"track == '{testTrack}' and lapnumber == 14")["sector1"]
)

24047    31.323
24091    31.012
24135    31.152
24179    30.851
24223    31.359
24267    31.439
24311    30.765
24355    45.406
24399    30.471
24443    31.368
24487    31.040
24531    31.156
24575    31.043
24619    31.505
24663    30.670
24707    31.394
24751    31.194
24795    30.541
24844    30.840
Name: sector1, dtype: float64

In [44]:
updated = (
    f1_team
    .query(f"full_name == '{testName}' and track == '{testTrack}'")
)

for key, value in updated.items():
    print(f"{key}: {value.values[0]}")

updated

driver: VER
lapnumber: 1.0
position: 9.0
laptime: 117.183
sector1: nan
sector2: 52.573
sector3: 29.298
maxspeed: 300.0
compound: MEDIUM
track: Belgium
full_name: Max Verstappen
team: Red Bull

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
24166,VER,1.0,9.0,117.183,NaN,52.573,29.298,300.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24167,VER,2.0,8.0,109.828,30.820,49.592,29.416,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24168,VER,3.0,8.0,110.141,30.975,49.693,29.473,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24169,VER,4.0,8.0,110.055,31.020,49.636,29.399,306.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24170,VER,5.0,8.0,110.138,31.118,49.599,29.421,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24171,VER,6.0,8.0,110.073,30.920,49.795,29.358,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24172,VER,7.0,8.0,110.146,31.044,49.700,29.402,307.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24173,VER,8.0,8.0,110.094,30.957,49.759,29.378,309.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24174,VER,9.0,8.0,110.609,30.938,50.214,29.457,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24175,VER,10.0,8.0,114.655,31.005,49.825,33.825,308.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24176,VER,11.0,13.0,122.789,45.573,48.109,29.107,310.0,HARD,Belgium,Max Verstappen,Red Bull
24177,VER,12.0,10.0,108.403,30.615,48.559,29.229,315.0,HARD,Belgium,Max Verstappen,Red Bull
24178,VER,13.0,9.0,108.431,31.082,48.239,29.110,312.0,HARD,Belgium,Max Verstappen,Red Bull
24179,VER,14.0,8.0,108.153,30.851,48.222,29.080,NaN,HARD,Belgium,Max Verstappen,Red Bull
24180,VER,15.0,8.0,108.229,30.811,48.342,29.076,313.0,HARD,Belgium,Max Verstappen,Red Bull
24181,VER,16.0,7.0,108.509,30.808,48.571,29.130,315.0,HARD,Belgium,Max Verstappen,Red Bull
24182,VER,17.0,7.0,108.431,30.753,48.584,29.094,311.0,HARD,Belgium,Max Verstappen,Red Bull
24183,VER,18.0,7.0,108.896,30.775,48.975,29.146,313.0,HARD,Belgium,Max Verstappen,Red Bull
24184,VER,19.0,7.0,108.578,30.879,48.583,29.116,314.0,HARD,Belgium,Max Verstappen,Red Bull
24185,VER,20.0,7.0,109.134,30.947,48.912,29.275,311.0,HARD,Belgium,Max Verstappen,Red Bull
24186,VER,21.0,5.0,109.273,30.823,49.246,29.204,314.0,HARD,Belgium,Max Verstappen,Red Bull
24187,VER,22.0,5.0,108.448,31.091,48.204,29.153,313.0,HARD,Belgium,Max Verstappen,Red Bull
24188,VER,23.0,5.0,108.494,31.211,48.197,29.086,312.0,HARD,Belgium,Max Verstappen,Red Bull
24189,VER,24.0,5.0,108.154,31.173,48.096,28.885,313.0,HARD,Belgium,Max Verstappen,Red Bull
24190,VER,25.0,5.0,107.921,31.127,47.886,28.908,314.0,HARD,Belgium,Max Verstappen,Red Bull
24191,VER,26.0,4.0,107.815,31.124,47.815,28.876,NaN,HARD,Belgium,Max Verstappen,Red Bull
24192,VER,27.0,3.0,107.431,31.032,47.549,28.850,315.0,HARD,Belgium,Max Verstappen,Red Bull
24193,VER,28.0,4.0,112.026,31.021,47.724,33.281,NaN,HARD,Belgium,Max Verstappen,Red Bull
24194,VER,29.0,7.0,120.489,45.265,46.585,28.639,311.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24195,VER,30.0,5.0,106.447,30.611,47.026,28.810,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24196,VER,31.0,5.0,106.363,30.950,46.698,28.715,310.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24197,VER,32.0,5.0,106.128,30.875,46.512,28.741,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24198,VER,33.0,5.0,106.417,30.904,46.670,28.843,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24199,VER,34.0,5.0,106.630,30.957,46.821,28.852,315.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24200,VER,35.0,5.0,107.009,30.947,47.264,28.798,314.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24201,VER,36.0,5.0,107.156,30.906,47.253,28.997,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24202,VER,37.0,5.0,107.200,30.765,47.596,28.839,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24203,VER,38.0,5.0,107.177,30.850,47.473,28.854,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24204,VER,39.0,5.0,107.244,30.883,47.479,28.882,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24205,VER,40.0,5.0,107.227,30.646,47.673,28.908,316.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24206,VER,41.0,5.0,107.354,30.598,47.920,28.836,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull
24207,VER,42.0,5.0,107.387,30.637,47.949,28.801,319.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24208,VER,43.0,5.0,107.102,30.579,47.831,28.692,317.0,MEDIUM,Belgium,Max Verstappen,Red Bull
24209,VER,44.0,5.0,106.899,30.605,47.569,28.725,NaN,MEDIUM,Belgium,Max Verstappen,Red Bull

In [45]:
float(updated.query('lapnumber == 5')['sector1'].values[0])

31.118

In [46]:
def get_best_time_on_sector(track, lap, sector):
    return float(f1_team.query(f"track == '{track}' and lapnumber == {lap}")[sector].min())

In [47]:
get_best_time_on_sector('Belgium', 14, 'sector1')

30.471

In [48]:
name, track = 'Max Verstappen', 'Monaco'

In [70]:
updated = (
    f1_team
    .query(f"full_name == '{name}' and track == '{track}'")
)
updated['sector1_color'] = 'green'
updated['sector2_color'] = 'blue'
updated['sector3_color'] = 'red'

best_lap = [500, 500, 500]
for lap in range(1, len(updated) + 1):
    i = 0
    for sector in ['sector1', 'sector2', 'sector3']:
        current = updated.query(f"lapnumber == {lap}")
        if current.empty:
            continue
        time = float(current[sector].values[0])
        if time < best_lap[i]:
            if time <= get_best_time_on_sector(track, lap, sector):
                updated.loc[current.index, f"{sector}_color"] = 'purple'
            else:
                updated.loc[current.index, f"{sector}_color"] = 'green'
            best_lap[i] = time
        else:
            updated.loc[current.index, f"{sector}_color"] = 'red'
        if sector == 'sector2':
            print(best_lap[i], time, get_best_time_on_sector(track, lap, sector))
        i += 1
updated

38.218 38.218 38.057
38.218 38.86 38.235
38.218 38.888 38.618
38.218 38.953 38.328
38.218 39.71 38.129
38.2 38.2 37.68
38.2 38.504 37.732
38.2 38.489 37.382
38.177 38.177 37.733
38.177 38.28 37.563
37.879 37.879 37.442
37.533 37.533 36.898
37.408 37.408 36.99
37.408 37.792 37.268
37.408 37.755 36.402
37.408 37.61 35.884
37.408 37.408 35.938
37.408 37.869 36.855
37.402 37.402 37.018
37.402 37.731 36.874
37.402 37.631 36.89
36.884 36.884 36.755
36.884 37.287 36.635
36.884 37.328 36.745
36.884 37.241 36.653
36.884 37.213 36.554
36.851 36.851 36.631
36.819 36.819 36.636
36.66 36.66 36.543
36.66 36.674 36.534
36.66 36.848 36.599
36.66 36.81 36.588
36.66 37.043 36.668
36.66 37.357 36.672
36.66 37.154 36.884
36.66 36.992 36.536
36.66 36.93 36.54
36.647 36.647 36.297
36.647 36.874 36.308
36.567 36.567 36.558
36.567 36.721 36.11
36.517 36.517 36.418
36.517 36.685 36.462
36.517 36.682 36.597
36.517 36.559 36.366
36.517 36.688 36.519
36.517 36.661 36.242
36.517 36.778 35.985
36.517 36.859 36.497
36.517 36.565 36.191
36.323 36.323 36.323
36.244 36.244 35.889
36.049 36.049 35.636
35.59 35.59 35.59
35.529 35.529 35.057
35.529 36.173 35.88
35.377 35.377 35.377
35.369 35.369 34.842
35.369 35.421 35.421
35.369 35.599 35.321
35.369 36.108 35.324
35.369 35.973 34.854
35.369 36.106 35.266
35.369 35.717 35.463
35.369 35.898 35.241
35.369 35.947 35.718
35.369 35.912 35.592
35.369 35.698 35.491
35.369 35.669 35.416
35.369 35.787 35.501
35.369 35.888 35.511
35.369 35.7 35.135
35.369 35.636 35.445
35.369 35.638 34.99
35.369 35.759 35.387
35.369 35.818 35.233

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team,sector1_color,sector2_color,sector3_color
19789,VER,2.0,6.0,NaN,24.134,38.218,95.091,255.0,MEDIUM,Monaco,Max Verstappen,Red Bull,purple,green,green
19790,VER,3.0,6.0,85.744,24.715,38.860,22.169,266.0,MEDIUM,Monaco,Max Verstappen,Red Bull,red,red,green
19791,VER,4.0,6.0,83.275,21.947,38.888,22.440,262.0,MEDIUM,Monaco,Max Verstappen,Red Bull,green,red,red
19792,VER,5.0,6.0,83.400,22.318,38.953,22.129,259.0,MEDIUM,Monaco,Max Verstappen,Red Bull,red,red,green
19793,VER,6.0,6.0,83.787,21.761,39.710,22.316,258.0,MEDIUM,Monaco,Max Verstappen,Red Bull,green,red,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19861,VER,74.0,6.0,75.380,19.602,35.636,20.142,283.0,HARD,Monaco,Max Verstappen,Red Bull,red,red,red
19862,VER,75.0,6.0,75.396,19.556,35.638,20.202,284.0,HARD,Monaco,Max Verstappen,Red Bull,red,red,red
19863,VER,76.0,6.0,75.641,19.673,35.759,20.209,285.0,HARD,Monaco,Max Verstappen,Red Bull,red,red,red
19864,VER,77.0,6.0,75.543,19.644,35.818,20.081,286.0,HARD,Monaco,Max Verstappen,Red Bull,red,red,red
19865,VER,78.0,6.0,76.248,19.697,36.263,20.288,286.0,HARD,Monaco,Max Verstappen,Red Bull,green,blue,red

In [71]:
f1_team.query('track == "Australia" and driver == "VER"')

,driver,lapnumber,position,laptime,sector1,sector2,sector3,maxspeed,compound,track,full_name,team
24875,VER,1.0,1.0,87.458,NaN,18.462,35.518,238.0,MEDIUM,Australia,Max Verstappen,Red Bull
24876,VER,2.0,2.0,84.099,29.623,18.375,36.101,281.0,MEDIUM,Australia,Max Verstappen,Red Bull
24877,VER,3.0,2.0,83.115,28.793,18.573,35.749,305.0,MEDIUM,Australia,Max Verstappen,Red Bull
24878,VER,4.0,19.0,NaN,28.756,18.353,NaN,302.0,MEDIUM,Australia,Max Verstappen,Red Bull

In [65]:
µ(
    f1_team
        .query(f'full_name == "{name}"')
        .groupby('track')
        .agg(
            position=('position', 'last')
        )
        .reset_index()
)

             track  position
0        Abu Dhabi       6.0
1           Austin       4.0
2        Australia      19.0
3          Austria       5.0
4       Azerbaijan       5.0
5          Barhain       1.0
6          Belgium       5.0
7           Brazil       1.0
8           Canada       1.0
9            China       1.0
10  Emilia Romagna       1.0
11   Great Britain       2.0
12         Hungary       5.0
13           Italy       6.0
14           Japan       1.0
15       Las Vegas       5.0
16          Mexico       6.0
17           Miami       2.0
18          Monaco       6.0
19      Netherland       2.0
20           Qatar       1.0
21    Saudi Arabia       1.0
22       Singapore       2.0
23           Spain       1.0